### ISSUE TITLE
callback.newPasswordRequired is not a function

### ISSUE THREAD

**Issue by hszeto** [AirLabsTeam/react-native-aws-cognito-js#1]
I followed this example. 

[https://github.com/AirLabsTeam/react-native-aws-cognito-js/blob/master/example/app.js](https://github.com/AirLabsTeam/react-native-aws-cognito-js/blob/master/example/app.js)

1. Replaced const appConfig with my configs.
2. Created a new Cognito User Pool and Federated Identity.
3. Manually created an user in Cognito User Pool dashboard. 
4. Fire up my React Native app.
5. Login.

I got this error in the console. "callback.newPasswordRequired is not a function"

How can I get around this?

Thanks

**Comment by jmparsons** [comment]
@hszeto This is a direct port of the official [Amazon Cognito Identity SDK for JavaScript](https://github.com/aws/amazon-cognito-identity-js).

This should help you out:

https://github.com/aws/amazon-cognito-identity-js/issues/175
