### ISSUE TITLE
On Android - TypeError: undefined is not an object (evaluating 'RNAWSCognito.computeModPow')

### ISSUE THREAD

**Issue by ramki1979** [AirLabsTeam/react-native-aws-cognito-js#13]
I am using `authenticateUser` on iOS and Android.

iOS is working fine. I am running into `TypeError: undefined is not an object (evaluating 'RNAWSCognito.computeModPow')` on android.

Anything I am missing here.

**Comment by jmparsons** [comment]
I would just make sure to run `react-native link` to make sure the android gradle file is set properly.

**Comment by ramki1979** [comment]
I have used react-native link, all other functions related to AWS userpool of the lib are working in android.

**Comment by gastonconcilio** [comment]
I am having the same issue for iOS, only seen it when running `authenticateUser` so far.

`TypeError: Cannot read property 'computeModPow' of undefined`

**Comment by gastonconcilio** [comment]
Never mind - I had my Linked Frameworks and Libraries messed up.

**Comment by jmparsons** [comment]
@ramki1979 Please try running the example Android project. If that works on your side, then I'd just say double check your version, wipe node modules etc. Let me know if it works for you.

**Comment by ramki1979** [comment]
@jmparsons I wil try it today and reply back.

**Comment by ramki1979** [comment]
I am using React-Native-Navigation from Wix, so I have to add the Package list myself in the MainApplication.java
And I somehow missed added the 
```Java
new RNAWSCognitoPackage()
```

This might be the problem.
As @jmparsons mentioned to relook at `react-native link` should have solved my problem. But some how I didn't find the packagelist missing this library.

I am only able to find after comparing Example project with mine and wondering how I missed that.

Thanks @jmparsons @gastonconcilio for quick reply.

**Comment by chinloongtan** [comment]
I encountered this issue as well. 
What I did was drag ```RNAWSCognito.xcodeproj``` to my xcode project libraries and add ```libRNAWSCognito.a``` to ```Build Phases```. (Basically manually linking it). Hope this information helps someone in the future.

**Comment by Twitchkidd** [comment]
I had this same problem and what I missed that I had to do was run ```pod install``` after react-native link <PACKAGE_NAME> as that had added ```pod 'RNAWSCognito', :path => '../node_modules/amazon-cognito-identity-js'``` to Podfile automatically, but I hadn't installed it, and sure enough: ```Installing JKBigInteger2 (0.0.5)
Installing RNAWSCognito (1.29.0)``` showed up in my terminal and now I've got user authentication flow on iOS and Android. Yay!
