### ISSUE TITLE
Broken on RN 0.47 update

### ISSUE THREAD

**Issue by geeknam** [AirLabsTeam/react-native-aws-cognito-js#16]
`:react-native-aws-cognito-js:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/app/node_modules/react-native-aws-cognito-js/android/src/main/java/com/airlabsinc/RNAWSCognitoPackage.java:18: error: method does not override or implement a method from a supertype
    @Override
`
Simple fix: remove `createJSModules` method. More on the RN update: https://github.com/facebook/react-native/releases/tag/v0.47.0

**Comment by jmparsons** [comment]
@geeknam Hey thanks for finding that. Up for a pull request? Might be a little bit before I can update.

**Comment by jmparsons** [comment]
@geeknam Actually I might jump on it now.

**Comment by stradap** [comment]
Just for add more info, this only happened on Android due to the breaking change. I'm using this package on iOS without problems.

**Comment by jmparsons** [comment]
@stradap @geeknam Thanks for the info! I uploaded a fix. Let me know if it works okay.

**Comment by stradap** [comment]
It's working for me, thanks, @jmparsons
