### ISSUE TITLE
React 0.47 compatibility

### ISSUE THREAD

**Issue by dannyshisler** [AirLabsTeam/react-native-aws-cognito-js#17]
The current release doesn't work in Android with RN 0.47+ because of these breaking changes:
https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8
https://github.com/facebook/react-native/commit/53d5504f4077bf7fb7cbf7c1edac7e2cbde5c964

I've temporarily fixed the problem by commenting out the first two @Override statements in ...\node_modules\react-native-aws-cognito-js\android\src\main\java\com\airlabsinc\RNAWSCognitoPackage.java

I'm not sure if this class is needed at all?

**Comment by jmparsons** [comment]
@dannyshisler Try 0.0.6 I just pushed the fix earlier.

**Comment by dannyshisler** [comment]
Thanks @jmparsons that's working for me.
