### ISSUE TITLE
undefined is not an object(evaluating 'RNAWSCognito.computeModPow')

### ISSUE THREAD

**Issue by ujosatXyZ** [AirLabsTeam/react-native-aws-cognito-js#20]
SignUp was Success but login have some error.

undefined is not an object(evaluating 'RNAWSCognito.computeModPow')

![screenshot_20180109-192943](https://user-images.githubusercontent.com/33728618/34724539-0ef062d8-f546-11e7-8448-a3121cf85935.jpg)

**Comment by tobiastornros** [comment]
Possible duplicate #3 #13 

Try `react-native link`

**Comment by AustinErck** [comment]
I'm getting the same issues on iOS on a brand new project, that I just setup.

**Comment by anthonyjoeseph** [comment]
I had a similar problem that `react-native link` didn't fix.

Somehow my xcode project got linked to the `RNAWSCognito.xcodeproj` from `amazon-cognito-identity-js` insead of the project of the same name from `react-native-aws-cognito-js`. For whatever reason, `react-native link` didn't fix this for me.

All I had to do was delete the bad reference in the "Libraries" section of my xcode project, and [link](https://facebook.github.io/react-native/docs/linking-libraries-ios.html) the proper one (found at `node_modules/react-native-aws-cognito-js/ios/RNAWSCognito.xcodeproj`)

**Comment by rpss2** [comment]
I have the same problem. `react-native link` command didnt' fix for me. I delete `node_modules/aws-sdk` folder and reinstall dependence, but the problem persist. I use Android.

**Comment by kuan0911** [comment]
I am using aws amplify not this. But I also encounter the same error. I fix it with `react-native link amazon-cognito-identity-js` and add `compile project(':amazon-cognito-identity-js')` to app/build.gradle  dependencies in android(I use android).

**Comment by FrankVio** [comment]
`react-native link amazon-cognito-identity-js`

this fixed the issue for me on ios, thanks @kuan0911 !

**Comment by duytq94** [comment]
I don't know why command link just effect on Android, iOS does nothing.
Then I have to link manually, so for people stuck issue like me:

1. Find RNAWSCognito.xcodeproj in node_modules folder and add to Libraries
   ![screen shot 2019-02-26 at 9 30 04 pm](https://user-images.githubusercontent.com/24253421/53420113-bd835f00-3a0d-11e9-96d5-953b7eaa2b5c.png)
2. Click on your main project file (the one that represents the .xcodeproj) select Build Phases and drag the static library from the Products folder inside the Library you are importing to Link Binary With Libraries
   ![screen shot 2019-02-26 at 9 31 13 pm](https://user-images.githubusercontent.com/24253421/53420188-e0ae0e80-3a0d-11e9-8731-9fe9b5c82eeb.png)
   Done.

**Comment by nabeelItilite** [comment]
I think this issue should be closed

**Comment by ObedAmpah** [comment]
I'm having this same issue with RN 61.5, amazon-cognito-identity-js 4.3.0 and a successful signup/login on ANDROID. I do not manually link, I use pod install.

**UPDATE: 06/12/2020**
This error is appearing in the log output on my running bundler (`react-native start`) when I attempt to **signIn** after a successful signUp on ANDROID. IOS is working without issue.

**Comment by ObedAmpah** [comment]
I was able to solve this issue and posted my solution on this SO article:

https://stackoverflow.com/questions/57231782/cannot-read-property-computemodpow-of-undefined/62352462#62352462

Thank you,
