### ISSUE TITLE
Custom attributes missing in the getUserAttributes response - AWS cognito

### ISSUE THREAD

**Issue by karandocs** [AirLabsTeam/react-native-aws-cognito-js#22]
```
const userData = { Username: username, Pool: userPool };
const cognitoUser = new AWS.CognitoIdentityServiceProvider.CognitoUser(userData);
cognitoUser.getUserAttributes(function(err, result) {
                        if (err) {
                            alert(err);
                            return;
                        }
                        console.log(result)
                        for (i = 0; i < result.length; i++) {
                            console.log('attribute ' + result[i].getName() + ' has value ' + result[i].getValue());
                        }
                    });

```
I have a custom field userType. I have set the read, write permission for the custom attribute. But in the response of getUserAttributes i am getting only standard attributes(sub, email_verified, email). How can i retrieve both the standard and custom attributes?

This is my response -

![screen shot 2018-02-09 at 12 00 07 pm](https://user-images.githubusercontent.com/17482704/36028171-06d402da-0dc4-11e8-8310-e86e3507a88b.png)

**Comment by vsaradas** [comment]
How did you resolve this. We are facing the same issue

**Comment by makkus183** [comment]
same here, i also cannot get Standard Attributes like `family_name` and `given_name`, only the three Attributes @karankrizz mentioned in his response
