### ISSUE TITLE
RNAWSCognito undefined, and computeModPow is not a function

### ISSUE THREAD

**Issue by kangks** [AirLabsTeam/react-native-aws-cognito-js#3]
I encountered undefined error when evaluating RNAWSCognito.computeModPow() in AuthenticationHelper.js, resolved by removing the {},

from
```
const { RNAWSCognito } = NativeModules;
```
to
```
const RNAWSCognito = NativeModules;
```

But now I encountered RNAWSCognito.computeModPow is not a function. Which dependency do I need for iOS?

**Comment by jmparsons** [comment]
@kangks Did you link the project? `react-native link`

**Comment by kangks** [comment]
It works in a totally new project. Probably I screwed up something in the old project. Thanks!

**Comment by kibagateaux** [comment]
Running `react-native link` fixed this issue for me.
