### ISSUE TITLE
New SDK Library

### ISSUE THREAD

**Issue by rdibona** [AirLabsTeam/react-native-aws-cognito-js#5]
Does this announcement have any impact on your project?
https://aws.amazon.com/blogs/developer/react-native-support-in-the-aws-sdk-for-javascript/

Thanks for all of your hard work.

**Comment by jmparsons** [comment]
No. It's why this library exists. We use it, check package json.

**Comment by jmparsons** [comment]
@rdibona This library helps by generating SRP_A fast on device for user pools. If you're not using cognito user pools or are not generating SRP_A then the native bridge isn't necessary.
