### ISSUE TITLE
CognitoIdentityCredentials return session undefined

### ISSUE THREAD

**Issue by hszeto** [AirLabsTeam/react-native-aws-cognito-js#6]
I ran the app.js from the example locally. Cognito returns the access token. However, when console logging Config.credentials, I got the following:

CognitoIdentityCredentials {expired: true, expireTime: null, accessKeyId: undefined, sessionToken: undefined, params: Object…}
accessKeyId:undefined
data:null
expireTime:null
expired:true
params:Object
sessionToken:undefined
_clientConfig:Object
_identityId:null
identityId:(...)
secretAccessKey:undefined
get identityId:function get()
set identityId:function set(identityId)
__proto__:Credentials

How do I get a valid session when an user login ?

**Comment by jmparsons** [comment]
@hszeto It's all in the [documentation](https://github.com/aws/amazon-cognito-identity-js/) **Use case 16**:

```js
const cognitoUser = new CognitoUser(userData);
cognitoUser.authenticateUser(authenticationDetails, {
  onSuccess: (result) => {
    console.log('access token + ' + result.getAccessToken().getJwtToken());
    Config.credentials = new CognitoIdentityCredentials({
      IdentityPoolId: appConfig.IdentityPoolId,
      Logins: {
        [`cognito-idp.${appConfig.region}.amazonaws.com/${appConfig.UserPoolId}`]: result.getIdToken().getJwtToken()
      }
    });
    alert('Success');
    console.log(Config.credentials);
    //now user is logged in - can get session here
    cognitoUser.getSession((error, result) => {
      if (error) {
        console.log(error);
      } else {
        console.log(result);
      }
    });
  },
  onFailure: (err) => {
    alert(err);
  },
});
```

**Comment by hszeto** [comment]
back to the example in app.js... I have the following in the checkUser function:

```
checkUser = () => {
    const poolData = {
      UserPoolId: appConfig.UserPoolId,
      ClientId: appConfig.ClientId
    };
    const userPool = new CognitoUserPool(poolData);

    userPool.storage.sync((err, result) => {
      if (err) {
        console.log(err);
      } else {
        console.log(result);

        const u = userPool.getCurrentUser();
        console.log( u );
      }
  }
```
In console, Session and signInUserSession are null. However, username is log correctly. How should I set the session? I assume the session is being stored after the first login...
